# Generated by Django 3.2.16 on 2024-11-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='Пусто', help_text='Заполните информацию о себе', null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Пусто', help_text='Заполните Имя', max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='Пусто', help_text='Заполните Фамилию', max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
