# Generated by Django 3.2.16 on 2024-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Код потдверждения'),
        ),
    ]
