# Generated by Django 3.2.16 on 2024-11-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
        ('reviews', '0003_alter_title_genre'),
    ]

    operations = [
    ]
